
[functions.paystack-transactions]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-transactions/deno.json"
entrypoint = "./functions/paystack-transactions/index.ts"

[functions.expire-temp-licenses]
enabled = true
verify_jwt = true
entrypoint = "./functions/expire-temp-licenses/index.ts"

[functions.seo-preview]
enabled = true
verify_jwt = false
entrypoint = "./functions/seo-preview/index.ts"
