
[functions.paystack-transactions]
enabled = true
verify_jwt = true
import_map = "./functions/paystack-transactions/deno.json"
entrypoint = "./functions/paystack-transactions/index.ts"

[functions.expire-temp-licenses]
enabled = true
verify_jwt = true
entrypoint = "./functions/expire-temp-licenses/index.ts"

[functions.seo-preview]
enabled = true
verify_jwt = false
entrypoint = "./functions/seo-preview/index.ts"

[functions.paystack-webhook]
enabled = true
verify_jwt = false
entrypoint = "./functions/paystack-webhook/index.ts"

[functions.confirm-manual-payment]
enabled = true
verify_jwt = true
entrypoint = "./functions/confirm-manual-payment/index.ts"

[functions.paystack-refund]
enabled = true
verify_jwt = true
entrypoint = "./functions/paystack-refund/index.ts"

[functions.send-email]
enabled = true
verify_jwt = true
entrypoint = "./functions/send-email/index.ts"

[functions.payment-reminders]
enabled = true
verify_jwt = true
entrypoint = "./functions/payment-reminders/index.ts"
