-- Create the calendar table
-- Note: User requested table name 'calander', but using 'calendar' for correct spelling.
-- You can rename it to 'calander' if strictly required.
create table if not exists calendar (
  id bigint generated by default as identity primary key,
  event_dates text not null,
  event_name text not null,
  city text not null,
  sapa_status text not null, -- Renamed from 'SAPA' to 'sapa_status' for clarity
  venue text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Turn on row level security
alter table calendar enable row level security;

-- Create a policy that allows anyone to read the calendar
create policy "Public calendar are viewable by everyone."
  on calendar for select
  using ( true );

-- Insert data from the image
insert into calendar (event_dates, event_name, city, sapa_status, venue) values
('7 - 8 February', 'Padel Odyssey Finals', 'Jhb', 'Gold', 'KCC'),
('13 - 15 March', 'Daytona Open', 'CT', 'S Gold', 'R&B CT'),
('21 - 22 March', 'Warren''s Pro Cup KCC', 'JHB', 'Gold', 'KCC'),
('25 - 29 March', 'KCC Cup - SAPA Major 1', 'Jhb', 'Major', 'KCC & 105 Central'),
('3 - 6 April', 'R&B Ladies', 'CT', 'Gold', 'R&B CT'),
('3 - 6 April', 'R&B Gold', 'JHB', 'Gold', 'R&B JHB'),
('3 - 6 April', 'Dream Padel Easter Cup', 'KZN', 'Gold', 'Umhlanga'),
('10 - 12 April', 'Golden Point Gold', 'PTA', 'Gold', 'Golden Point'),
('16 - 19 April', 'Cape Town Major 2', 'CT', 'Major', 'R&B CT'),
('24 - 26 April', 'Gayle Pretoria', 'PTA', 'Gold', 'Gayle PTA'),
('25 - 27 April', 'Padel GQ Gold', 'PE', 'Gold', 'Padel GQ'),
('30 Apr - 3 May', 'Vaal Open', 'VAAL', 'Gold', '10by20 Vanderbijl'),
('8 - 10 May', 'Chiquita Cup & Cubs', 'JHB', 'Key Event', 'KCC'),
('8 - 10 May', 'R&B CT Men''s Open', 'CT', 'Gold', 'R&B CT'),
('8 - 10 May', 'R&B Jhb Men''s & 40+', 'JHB', 'Gold', 'R&B JHB'),
('15 - 17 May', 'North vs South Invitational', 'CT', 'Key Event', 'Camps Bay'),
('22 - 24 May', 'Arturf Gold', 'CT', 'S Gold', 'Arturf'),
('29 - 31 May', 'Virgin PTA Gold', 'PTA', 'Gold', 'VP Groenkloof'),
('29 - 31 May', 'Aura Gold', 'CT', 'Gold', 'Aura'),
('5 - 7 June', 'Capital Gold Pretoria', 'PTA', 'Gold', 'Net Padel'),
('5 - 7 June', 'Karibu Pro', 'KZN', 'Gold', 'Karibu'),
('12 - 14 June', 'Premier Padel Qualifier TBC', 'JHB', 'Gold', 'TBC'),
('13 June', 'SSPC Open', 'JHB', 'Gold', 'Netset Sandton'),
('19 - 21 June', 'R&B Ladies Gold', 'CT', 'Gold', 'R&B CT'),
('19 - 21 June', 'Virgin Lonehill/Belair', 'JHB', 'Gold', 'VP Bel Air / Lonehill'),
('19 - 21 June', 'Gayle Durban', 'KZN', 'Gold', 'Gayle Durban'),
('26 - 27 June', 'Padel Fiesta', 'BLOEM', 'S Gold', 'Ramblers'),
('26 - 27 June', 'Aura Gold', 'CT', 'Gold', 'Aura'),
('27 June', 'Padelbros Silver', 'POTCH', 'Silver', 'Potch'),
('3 - 5 July', 'R&B Gold Men''s', 'CT', 'Gold', 'R&B CT'),
('10 - 12 July', 'SA Championships Major 3', 'JHB', 'Major', 'JHB - TBC'),
('17 - 19 July', 'Atlantic Padel Gold', 'CT', 'Gold', 'Atlantic Padel'),
('26 July - 2 Aug', 'Premier Padel P2', 'PTA', 'FIP event', 'Sun Square Arena'),
('27 - 30 Aug', 'Durban Major 4', 'KZN', 'Major', 'VP Gateway, Umhlanga'),
('24 Sep - 1 Oct', 'SAPA Nationals Major 5', 'Bloem', 'Major', 'Bloem TBC');
