-- Create Players Table
create table players (
  id bigint generated by default as identity primary key,
  name text not null,
  rank_label text, -- e.g. "SAPA Rank #1"
  points int default 0,
  win_rate text, -- e.g. "88%"
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Events Table (Calendar)
create table events (
  id bigint generated by default as identity primary key,
  title text not null,
  date date not null, -- e.g. 2026-02-13
  time text, -- e.g. "08:00 AM"
  location text,
  category text, -- e.g. "SAPA Bronze"
  status text default 'upcoming', -- 'upcoming', 'completed', 'live'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table players enable row level security;
alter table events enable row level security;

-- Create Policy: Allow Public Read Access
create policy "Public players are viewable by everyone."
  on players for select
  using ( true );

create policy "Public events are viewable by everyone."
  on events for select
  using ( true );

-- Create Policy: Allow Authenticated Users (Admins) to Insert/Update/Delete
create policy "Admins can insert players."
  on players for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update players."
  on players for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete players."
  on players for delete
  using ( auth.role() = 'authenticated' );

create policy "Admins can insert events."
  on events for insert
  with check ( auth.role() = 'authenticated' );

create policy "Admins can update events."
  on events for update
  using ( auth.role() = 'authenticated' );

create policy "Admins can delete events."
  on events for delete
  using ( auth.role() = 'authenticated' );
