import { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, FlatList, Modal, Pressable, ScrollView, TextInput, View } from 'react-native';
import { Image } from 'expo-image';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { EventText as Text, EventIcon, Fade, WebsiteHeader, lime } from '@/components/events/website-ui';
import { Avatar, RankingDetails } from '@/components/rankings/ranking-details';
import { categoriesFor, fetchRankingProfiles, fetchRankings, organisations, type RankingPlayer } from '@/lib/rankings';
import { rankingTiers } from '@/lib/website/ranking-tiers';
import { useTabScenePadding } from '@/hooks/use-tab-scene-padding';
const muted='#65726B';
export function LocalRankings({ embedded = false, query = '', gender = 'men' }: { embedded?: boolean; query?: string; gender?: string }){
 const safe=useSafeAreaInsets();const bottom=useTabScenePadding();const list=useRef<FlatList<RankingPlayer>>(null);
 const [org,setOrg]=useState(15809);const [categoryIndex,setCategoryIndex]=useState(0);const [mainTab,setMainTab]=useState('Rankings');const [search,setSearch]=useState('');const [page,setPage]=useState(1);const [showOrgs,setShowOrgs]=useState(false);const [players,setPlayers]=useState<RankingPlayer[]>([]);const [profiles,setProfiles]=useState<Awaited<ReturnType<typeof fetchRankingProfiles>>>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [reload,setReload]=useState(0);const [selected,setSelected]=useState<RankingPlayer|null>(null);
 const categories=categoriesFor(org);const category=categories[embedded ? (gender === 'women' ? 1 : 0) : categoryIndex]||categories[0];
 const activeSearch=embedded?query:search;
 useEffect(()=>{setPage(1);},[query,gender]);
 useEffect(()=>{let live=true;fetchRankingProfiles().then(p=>{if(live)setProfiles(p);}).catch(()=>{});return()=>{live=false;};},[]);
 useEffect(()=>{let live=true;setLoading(true);setError('');setPlayers([]);fetchRankings(org,category).then(rows=>{if(live)setPlayers(rows);}).catch(()=>{if(live)setError('Rankings could not be loaded. Please try again.');}).finally(()=>{if(live)setLoading(false);});return()=>{live=false;};},[org,category.id,reload]);
 const enriched=useMemo(()=>{const byName=new Map(profiles.map(p=>[p.name.trim().toLowerCase(),p]));return players.map(p=>({...p,profile:byName.get(p.name.trim().toLowerCase())}));},[players,profiles]);
 const filtered=useMemo(()=>enriched.filter(p=>p.name.toLowerCase().includes(activeSearch.trim().toLowerCase())),[enriched,activeSearch]);const pages=Math.max(1,Math.ceil(filtered.length/20));const rows=filtered.slice((page-1)*20,page*20);
 const tableOffset=useRef(0);
 const movePage=(n:number)=>{setPage(n);list.current?.scrollToOffset({offset:tableOffset.current,animated:true});};
 return <View style={{flex:1,backgroundColor:'#F5F6F3',paddingTop:embedded?0:safe.top}}>{!embedded&&<WebsiteHeader/>}<FlatList ref={list} data={mainTab==='Rankings'?rows:[]} keyExtractor={p=>p.id} keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" contentContainerStyle={{paddingBottom:bottom}} refreshing={loading&&players.length>0} onRefresh={()=>setReload(x=>x+1)}
 ListHeaderComponent={<>
 {!embedded&&<View style={{paddingHorizontal:16,paddingTop:8,paddingBottom:20}}>
 <View style={{padding:12,borderRadius:16,backgroundColor:'#FFFFFF',borderWidth:1,borderColor:'#16251f18'}}><View style={{flexDirection:'row',alignItems:'center',paddingHorizontal:12,gap:10,backgroundColor:'#16251f0d',borderWidth:1,borderColor:'#16251f18',borderRadius:12}}><EventIcon name="magnifyingglass" color={muted}/><TextInput accessibilityLabel="Search player name" placeholder="Search player name..." placeholderTextColor="#6b7280" value={search} onChangeText={v=>{setSearch(v);setPage(1);}} autoCorrect={false} style={{flex:1,color:'#16251F',fontFamily:'ui-rounded',fontSize:16,height:46}}/>{!!search&&<Pressable accessibilityLabel="Clear search" onPress={()=>{setSearch('');setPage(1);}}><Text style={{color:muted,fontSize:20}}>×</Text></Pressable>}</View></View>
 <View style={{flexDirection:'row',gap:8,marginTop:12}}><Pressable accessibilityRole="button" accessibilityLabel="Select ranking organisation" onPress={()=>setShowOrgs(true)} style={{flex:1,minHeight:44,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:10,borderRadius:8,backgroundColor:'#16251f0d',borderWidth:1,borderColor:'#16251f18'}}>{org!==16482&&<Image source={org===15809?require('@/assets/sapa-logo.svg'):require('@/assets/images/BrollLogo.png')} style={{width:16,height:16,marginRight:6}} contentFit="contain"/>}<Text numberOfLines={1} style={{fontSize:11,flex:1}}>Official {organisations.find(o=>o.id===org)?.label} Rankings</Text><EventIcon name="chevron.down" size={12} color={muted}/></Pressable><View style={{flexDirection:'row',backgroundColor:'#16251f0d',padding:4,borderRadius:12,borderWidth:1,borderColor:'#16251f18'}}>{['Overview','Rankings'].map(t=><Pressable key={t} accessibilityRole="tab" accessibilityState={{selected:mainTab===t}} onPress={()=>setMainTab(t)} style={{paddingHorizontal:10,justifyContent:'center',borderRadius:8,backgroundColor:mainTab===t?lime:'transparent'}}><Text style={{fontSize:9,color:mainTab===t?'#000':muted}}>{t.toUpperCase()}</Text></Pressable>)}</View></View></View>}
 {mainTab==='Overview'?<RankingOverview/>:<>{!embedded&&<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{paddingHorizontal:16,gap:6,paddingBottom:24,flexGrow:1}}>{categories.map((c,i)=><Pressable key={c.id} accessibilityRole="tab" accessibilityState={{selected:categoryIndex===i}} onPress={()=>{setCategoryIndex(i);setPage(1);}} style={{flex:org===16482?undefined:1,alignItems:'center',paddingHorizontal:28,paddingVertical:12,borderRadius:10,backgroundColor:categoryIndex===i?lime:'#16251f0d'}}><Text style={{color:categoryIndex===i?'#000':muted,fontSize:10}}>{c.label.toUpperCase()}</Text></Pressable>)}</ScrollView>}
 <View onLayout={e=>{tableOffset.current=e.nativeEvent.layout.y;}} style={{marginHorizontal:16,padding:16,flexDirection:'row',backgroundColor:'#FFFFFF',borderTopLeftRadius:16,borderTopRightRadius:16,borderWidth:1,borderColor:'#16251f18'}}><Text style={{width:28,fontSize:11,color:muted}}>#</Text><Text style={{flex:1,fontSize:11,color:muted}}>PLAYER</Text><Text style={{width:62,fontSize:11,color:muted,textAlign:'right'}}>POINTS</Text><Text style={{width:52,fontSize:11,color:muted,textAlign:'right'}}>CHANGE</Text></View>
 {loading?<ActivityIndicator style={{padding:30}} color={lime}/>:error?<Pressable onPress={()=>setReload(x=>x+1)} style={{padding:24}}><Text>{error}</Text><Text style={{color:"#386018",marginTop:12}}>Retry</Text></Pressable>:!filtered.length?<Text style={{padding:24,color:muted}}>{activeSearch.trim()?`No players found matching “${activeSearch.trim()}”.`:'No rankings available for this category.'}</Text>:null}</>}
 </>}
 renderItem={({item:p})=><Pressable accessibilityRole="button" accessibilityLabel={`Rank ${p.rank}, ${p.name}, ${p.points} points. View ranking details`} onPress={()=>setSelected(p)} style={{marginHorizontal:16,paddingHorizontal:16,paddingVertical:13,flexDirection:'row',alignItems:'center',backgroundColor:'#FFFFFF',borderBottomWidth:1,borderColor:'#16251f10'}}><Text style={{width:28,fontSize:14}}>{p.rank}</Text><View style={{flex:1,flexDirection:'row',gap:8,alignItems:'center'}}><Avatar player={p} size={24}/><Text style={{flex:1,fontSize:14,lineHeight:20}}>{p.name}</Text></View><Text style={{width:62,fontSize:12,color:"#386018",textAlign:'right'}}>{p.points.toLocaleString()}</Text><Text style={{width:52,fontSize:11,color:p.change>0?'#24713C':p.change<0?'#B7352D':muted,textAlign:'right'}}>{p.change>0?`↑ ${p.change}`:p.change<0?`↓ ${Math.abs(p.change)}`:'—'}</Text></Pressable>}
 ListFooterComponent={mainTab==='Rankings'&&!loading&&filtered.length>0?<View style={{padding:20,gap:12}}><Text style={{fontSize:11,color:muted,textAlign:'center'}}>Showing {(page-1)*20+1}–{Math.min(page*20,filtered.length)} of {filtered.length} players</Text><View style={{flexDirection:'row',justifyContent:'center',gap:8}}><PageButton label="‹" disabled={page===1} onPress={()=>movePage(page-1)}/>{Array.from({length:Math.min(pages,5)},(_,i)=>Math.max(1,Math.min(page-2,pages-4))+i).map(n=><PageButton key={n} label={String(n)} selected={page===n} onPress={()=>movePage(n)}/>)}<PageButton label="›" disabled={page===pages} onPress={()=>movePage(page+1)}/></View></View>:null}/>
 <Modal visible={showOrgs} transparent animationType="slide" onRequestClose={()=>setShowOrgs(false)}><View style={{flex:1,justifyContent:'flex-end',backgroundColor:'#0009'}}><Pressable style={{flex:1}} accessibilityLabel="Close organisation selector" onPress={()=>setShowOrgs(false)}/><View style={{backgroundColor:'#FFFFFF',padding:24,paddingBottom:safe.bottom+24,borderTopLeftRadius:24,borderTopRightRadius:24,gap:12}}><Text style={{fontSize:18,marginBottom:8}}>Ranking organisation</Text>{organisations.map(o=><Pressable key={o.id} onPress={()=>{setOrg(o.id);setCategoryIndex(0);setPage(1);setShowOrgs(false);}} style={{paddingVertical:16,flexDirection:'row',justifyContent:'space-between'}}><Text style={{fontSize:14}}>Official {o.label} Rankings</Text>{o.id===org&&<EventIcon name="checkmark"/>}</Pressable>)}</View></View></Modal>
 {selected&&<RankingDetails player={selected} age={category.age} onClose={()=>setSelected(null)}/>}</View>;
}
function PageButton({label,disabled,selected,onPress}:{label:string;disabled?:boolean;selected?:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityLabel={`Page ${label}`} disabled={disabled} onPress={onPress} style={{width:44,height:44,alignItems:'center',justifyContent:'center',borderRadius:8,backgroundColor:selected?lime:'#16251f0d',opacity:disabled?.3:1}}><Text style={{color:selected?'#000':'#fff',fontSize:13}}>{label}</Text></Pressable>;}
function RankingOverview(){const [open,setOpen]=useState('');return <View style={{padding:16,gap:16}}>{[['Play Tournaments','Compete in SAPA sanctioned events across various tiers, from Bronze up to Major.'],['Earn Points','Your performance dictates your points. Higher tier events offer significantly larger rewards.'],['Climb the Ranks','Only your Best 8 tournaments count towards your official national ranking. (Cat 3 & 4 proportionate where applicable)']].map(([title,body])=><View key={title} style={{padding:24,borderRadius:24,borderWidth:1,borderColor:'#16251f18',backgroundColor:'#16251f05',gap:12}}><EventIcon name="trophy" size={28}/><Text style={{fontSize:18}}>{title}</Text><Text style={{fontSize:14,lineHeight:21,color:muted}}>{body}</Text></View>)}<Text style={{fontSize:24,marginTop:20}}>Points Breakdown for official SAPA Rankings 2026</Text><Text style={{fontSize:14,color:muted}}>Expand each tier to see detailed point structures by category.</Text>{rankingTiers.map((tier,i)=><View key={tier.type} style={{borderWidth:1,borderColor:'#16251f18',borderRadius:20,overflow:'hidden',backgroundColor:'#FFFFFF'}}><Pressable accessibilityRole="button" accessibilityState={{expanded:open===tier.type}} onPress={()=>setOpen(open===tier.type?'':tier.type)} style={{padding:20,flexDirection:'row',gap:12,alignItems:'center'}}><EventIcon name="trophy" color={['#ef4444','#f59e0b','#facc15','#52625A','#c2410c'][i]} size={24}/><View style={{flex:1,gap:4}}><Text>{tier.type}</Text><Text style={{fontSize:12,color:muted}}>Up to {tier.maxPoints} points</Text></View><EventIcon name={open===tier.type?'chevron.down':'chevron.right'} color={muted}/></Pressable>{open===tier.type&&<ScrollView horizontal><View><View style={{flexDirection:'row',padding:12}}>{['Category',...(tier.headers||['Winner','Finalist','Semi-final','Quarter-final','Round of 16','Round of 32'])].map(h=><Text key={h} style={{width:105,fontSize:10,color:muted}}>{h}</Text>)}</View>{tier.rows.map(row=><View key={row.cat} style={{flexDirection:'row',padding:12,borderTopWidth:1,borderColor:'#16251f10'}}>{[row.cat,...('points'in row?row.points:[row.winner,row.finals,row.semis,row.quarters,row.r16,row.r32])].map((v,j)=><Text key={j} style={{width:105,fontSize:13}}>{v}</Text>)}</View>)}</View></ScrollView>}</View>)}</View>;}
